# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 00:24
from __future__ import unicode_literals

from django.db import migrations


def create_initial_authors(apps, schema):
    Author = apps.get_model('testapp.Author')
    Author.objects.create(
        name="Fred Johnston",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=create_initial_authors)
    ]
