# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20180220_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=1000)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='citation',
            name='metadata',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Contact'),
        ),
    ]
